// thum.io generates a free screenshot of any URL — no API key needed
// Format: https://image.thum.io/get/width/400/crop/250/<game_url>
const thumb = (url) =>
  `https://image.thum.io/get/width/400/crop/250/${url}`;

export const GAMES = [
  // ── Happy ──
  {
    id: "happyville-merge-farm",
    name: "Happyville Merge Farm",
    mood: "happy",
    tags: ["casual", "merge", "farm"],
    src: "https://games.crazygames.com/en_US/happyville-merge-farm-gtu/index.html",
    thumb: "https://games.crazygames.com/en_US/happyville-merge-farm-gtu/index.html",
  },
  {
    id: "skydom-reforged",
    name: "Skydom Reforged",
    mood: "happy",
    tags: ["puzzle", "match"],
    src: "https://games.crazygames.com/en_US/skydom-reforged/index.html",
    thumb: "https://games.crazygames.com/en_US/skydom-reforged/index.html",
  },
  {
    id: "fortzone-battle-royale",
    name: "Fortzone Battle Royale",
    mood: "happy",
    tags: ["action", "battle royale"],
    src: "https://games.crazygames.com/en_US/fortzone-battle-royale-xkd/index.html",
    thumb: thumb("https://games.crazygames.com/en_US/fortzone-battle-royale-xkd/index.html"),
  },
  {
    id: "pulse-ball",
    name: "Pulse Ball",
    mood: "happy",
    tags: ["arcade", "reflex"],
    src: "https://games.crazygames.com/en_US/pulse-ball/index.html",
    thumb: thumb("https://games.crazygames.com/en_US/pulse-ball/index.html"),
  },
  {
    id: "ragdoll-archers",
    name: "Ragdoll Archers",
    mood: "happy",
    tags: ["action", "physics"],
    src: "https://games.crazygames.com/en_US/ragdoll-archers/index.html",
    thumb: thumb("https://games.crazygames.com/en_US/ragdoll-archers/index.html"),
  },
  {
    id: "dragon-simulator-3d",
    name: "Dragon Simulator 3D",
    mood: "happy",
    tags: ["simulation", "3d"],
    src: "https://games.crazygames.com/embed/dragon-simulator-3d/index.html",
    thumb: thumb("https://games.crazygames.com/embed/dragon-simulator-3d/index.html"),
  },
  {
    id: "bubble-blast",
    name: "Bubble Blast",
    mood: "happy",
    tags: ["casual", "bubble"],
    src: "https://games.crazygames.com/en_US/bubble-blast-pwd/index.html",
    thumb: thumb("https://games.crazygames.com/en_US/bubble-blast-pwd/index.html"),
  },
  {
    id: "count-masters",
    name: "Count Masters",
    mood: "happy",
    tags: ["casual", "runner"],
    src: "https://games.crazygames.com/en_US/count-masters-stickman-games/index.html",
    thumb: thumb("https://games.crazygames.com/en_US/count-masters-stickman-games/index.html"),
  },
  {
    id: "racing-limits",
    name: "Racing Limits",
    mood: "happy",
    tags: ["racing", "cars"],
    src: "https://games.crazygames.com/en_US/racing-limits/index.html",
    thumb: thumb("https://games.crazygames.com/en_US/racing-limits/index.html"),
  },
  {
    id: "duck-life-space",
    name: "Duck Life Space",
    mood: "happy",
    tags: ["adventure", "casual"],
    src: "https://games.crazygames.com/en_US/duck-life-space/index.html",
    thumb: thumb("https://games.crazygames.com/en_US/duck-life-space/index.html"),
  },
  {
    id: "ludo-king",
    name: "Ludo King",
    mood: "happy",
    tags: ["board", "multiplayer"],
    src: "https://games.crazygames.com/en_US/ludo-king/index.html",
    thumb: thumb("https://games.crazygames.com/en_US/ludo-king/index.html"),
  },

  // ── Angry ──
  {
    id: "iron-legion",
    name: "Iron Legion",
    mood: "angry",
    tags: ["strategy", "war"],
    src: "https://games.crazygames.com/en_US/iron-legion/index.html",
    thumb: thumb("https://games.crazygames.com/en_US/iron-legion/index.html"),
  },
  {
    id: "zombiecraft-io",
    name: "ZombieCraft.io",
    mood: "angry",
    tags: ["survival", "multiplayer"],
    src: "https://games.crazygames.com/en_US/zombiecraftio/index.html",
    thumb: thumb("https://games.crazygames.com/en_US/zombiecraftio/index.html"),
  },
  {
    id: "gun-master-3d",
    name: "Gun Master 3D",
    mood: "angry",
    tags: ["fps", "shooting"],
    src: "https://games.crazygames.com/en_US/gun-master-3d---fps-shooting-game/index.html",
    thumb: thumb("https://games.crazygames.com/en_US/gun-master-3d---fps-shooting-game/index.html"),
  },
  {
    id: "unmatched-basketball",
    name: "Unmatched Basketball",
    mood: "angry",
    tags: ["sports", "basketball"],
    src: "https://games.crazygames.com/en_US/unmatched-basketball/index.html",
    thumb: thumb("https://games.crazygames.com/en_US/unmatched-basketball/index.html"),
  },
  {
    id: "8-ball-pool",
    name: "8-Ball Pool",
    mood: "angry",
    tags: ["sports", "pool"],
    src: "https://games.crazygames.com/en_US/8-ball-pool-wyr/index.html",
    thumb: thumb("https://games.crazygames.com/en_US/8-ball-pool-wyr/index.html"),
  },
  {
    id: "doomsday-shooter",
    name: "Doomsday Shooter",
    mood: "angry",
    tags: ["shooter", "survival"],
    src: "https://games.crazygames.com/en_US/doomsday-shooter/index.html",
    thumb: thumb("https://games.crazygames.com/en_US/doomsday-shooter/index.html"),
  },
  {
    id: "path-of-survivor",
    name: "Path of Survivor",
    mood: "angry",
    tags: ["rpg", "survival"],
    src: "https://games.crazygames.com/en_US/path-of-survivor/index.html",
    thumb: thumb("https://games.crazygames.com/en_US/path-of-survivor/index.html"),
  },
  {
    id: "traffic-rider",
    name: "Traffic Rider",
    mood: "angry",
    tags: ["racing", "bike"],
    src: "https://games.crazygames.com/en_US/traffic-rider-vvq/index.html",
    thumb: thumb("https://games.crazygames.com/en_US/traffic-rider-vvq/index.html"),
  },
  {
    id: "mx-offroad-master",
    name: "MX Offroad Master",
    mood: "angry",
    tags: ["racing", "offroad"],
    src: "https://games.crazygames.com/en_US/mx-offroad-master/index.html",
    thumb: thumb("https://games.crazygames.com/en_US/mx-offroad-master/index.html"),
  },

  // ── Sad ──
  {
    id: "tile-farm-story",
    name: "Tile Farm Story",
    mood: "sad",
    tags: ["casual", "matching"],
    src: "https://games.crazygames.com/en_US/tile-farm-story-matching-game/index.html",
    thumb: thumb("https://games.crazygames.com/en_US/tile-farm-story-matching-game/index.html"),
  },
  {
    id: "neko-cat-puzzle",
    name: "Neko Cat Puzzle",
    mood: "sad",
    tags: ["puzzle", "cute"],
    src: "https://games.crazygames.com/en_US/neko-sliding-cat-puzzle/index.html",
    thumb: thumb("https://games.crazygames.com/en_US/neko-sliding-cat-puzzle/index.html"),
  },
  {
    id: "wood-block-journey",
    name: "Wood Block Journey",
    mood: "sad",
    tags: ["puzzle", "relaxing"],
    src: "https://games.crazygames.com/en_US/wood-block-journey/index.html",
    thumb: thumb("https://games.crazygames.com/en_US/wood-block-journey/index.html"),
  },
  {
  id: "evo-fish",
  name: "Evo Fish",
  mood: "sad",
  tags: ["clicker", "merge", "casual"],
  src: "https://games.crazygames.com/en_US/evo-fish/index.html",
},
{
  id: "merge-world",
  name: "Merge World",
  mood: "sad",
  tags: ["merge", "casual", "relaxing"],
  src: "https://games.crazygames.com/en_US/merge-world/index.html",
},{
  id: "lucys-ville",
  name: "Lucy's Ville",
  mood: "sad",
  tags: ["merge", "adventure", "casual"],
  src: "https://games.crazygames.com/en_US/lucy-s-ville-gsi/index.html",
},
  {
    id: "merge-academy",
    name: "Merge Academy",
    mood: "sad",
    tags: ["casual", "merge"],
    src: "https://games.crazygames.com/en_US/merge-academy/index.html",
    thumb: thumb("https://games.crazygames.com/en_US/merge-academy/index.html"),
  },
  {
    id: "connect-the-dots",
    name: "Connect the Dots",
    mood: "sad",
    tags: ["puzzle", "relaxing"],
    src: "https://games.crazygames.com/en_US/connect-the-dots---relaxing-puzzle/index.html",
    thumb: thumb("https://games.crazygames.com/en_US/connect-the-dots---relaxing-puzzle/index.html"),
  },
  {
    id: "sprout-valley",
    name: "Sprout Valley",
    mood: "sad",
    tags: ["farming", "casual"],
    src: "https://games.crazygames.com/en_US/sprout-valley/index.html",
    thumb: thumb("https://games.crazygames.com/en_US/sprout-valley/index.html"),
  },
  {
    id: "solitaire-home-story",
    name: "Solitaire Home Story",
    mood: "sad",
    tags: ["card", "solitaire"],
    src: "https://games.crazygames.com/en_US/solitaire-home-story/index.html",
    thumb: thumb("https://games.crazygames.com/en_US/solitaire-home-story/index.html"),
  },
  {
    id: "syntaxia",
    name: "Syntaxia",
    mood: "sad",
    tags: ["puzzle", "word"],
    src: "https://games.crazygames.com/en_US/syntaxia/index.html",
    thumb: thumb("https://games.crazygames.com/en_US/syntaxia/index.html"),
  },

  // ── Neutral ──
  {
    id: "slingshot-fortress",
    name: "Slingshot Fortress",
    mood: "neutral",
    tags: ["physics", "strategy"],
    src: "https://games.crazygames.com/en_US/slingshot-fortress/index.html",
    thumb: thumb("https://games.crazygames.com/en_US/slingshot-fortress/index.html"),
  },
  {
    id: "chess",
    name: "Chess",
    mood: "neutral",
    tags: ["board", "strategy"],
    src: "https://games.crazygames.com/en_US/chess-free/index.html",
    thumb: thumb("https://games.crazygames.com/en_US/chess-free/index.html"),
  },
  {
    id: "skillwarz",
    name: "Skillwarz",
    mood: "neutral",
    tags: ["fps", "multiplayer"],
    src: "https://games.crazygames.com/en_US/skillwarz/index.html",
    thumb: thumb("https://games.crazygames.com/en_US/skillwarz/index.html"),
  },
  {
    id: "tankcraft",
    name: "Tankcraft",
    mood: "neutral",
    tags: ["strategy", "tanks"],
    src: "https://games.crazygames.com/en_US/tankcraft/index.html",
    thumb: thumb("https://games.crazygames.com/en_US/tankcraft/index.html"),
  },
  {
    id: "merge-to-battle",
    name: "Merge to Battle",
    mood: "neutral",
    tags: ["strategy", "merge"],
    src: "https://games.crazygames.com/en_US/merge-to-battle/index.html",
    thumb: thumb("https://games.crazygames.com/en_US/merge-to-battle/index.html"),
  },
  {
    id: "hedgies",
    name: "Hedgies",
    mood: "neutral",
    tags: ["casual", "cute"],
    src: "https://games.crazygames.com/en_US/hedgies/index.html",
    thumb: thumb("https://games.crazygames.com/en_US/hedgies/index.html"),
  },
  {
    id: "scavenger-hunt",
    name: "Scavenger Hunt",
    mood: "neutral",
    tags: ["multiplayer", "adventure"],
    src: "https://games.crazygames.com/en_US/scavenger-hunt---multiplayer/index.html",
    thumb: thumb("https://games.crazygames.com/en_US/scavenger-hunt---multiplayer/index.html"),
  },
  {
    id: "screw-out",
    name: "Screw Out",
    mood: "neutral",
    tags: ["puzzle", "casual"],
    src: "https://games.crazygames.com/en_US/screw-out-bolts-and-nuts/index.html",
    thumb: thumb("https://games.crazygames.com/en_US/screw-out-bolts-and-nuts/index.html"),
  },
  {
  id: "obby-challenge-prison-run",
  name: "Obby Challenge Prison Run",
  mood: "neutral",
  tags: ["platformer", "casual"],
  src: "https://games.crazygames.com/en_US/obby-challenge-prison-run/index.html",
},

  // ── Surprised ──
  {
    id: "horse-family-simulator",
    name: "Horse Family Simulator",
    mood: "surprised",
    tags: ["simulation", "animals"],
    src: "https://games.crazygames.com/en_US/horse-family-animal-simulator-3d/index.html",
    thumb: thumb("https://games.crazygames.com/en_US/horse-family-animal-simulator-3d/index.html"),
  },
  {
    id: "miniblox",
    name: "Miniblox",
    mood: "surprised",
    tags: ["building", "multiplayer"],
    src: "https://games.crazygames.com/en_US/miniblox/index.html",
    thumb: thumb("https://games.crazygames.com/en_US/miniblox/index.html"),
  },
  {
    id: "bloxdhop-io",
    name: "BloxdHop.io",
    mood: "surprised",
    tags: ["platformer", "multiplayer"],
    src: "https://games.crazygames.com/en_US/bloxdhop-io/index.html",
    thumb: thumb("https://games.crazygames.com/en_US/bloxdhop-io/index.html"),
  },
  {
    id: "heroes-assemble",
    name: "Heroes Assemble",
    mood: "surprised",
    tags: ["action", "strategy"],
    src: "https://games.crazygames.com/en_US/heroes-assemble/index.html",
    thumb: thumb("https://games.crazygames.com/en_US/heroes-assemble/index.html"),
  },
  {
    id: "mahjongg-solitaire",
    name: "Mahjongg Solitaire",
    mood: "surprised",
    tags: ["board", "puzzle"],
    src: "https://games.crazygames.com/en_US/mahjongg-solitaire/index.html",
    thumb: thumb("https://games.crazygames.com/en_US/mahjongg-solitaire/index.html"),
  },
  {
    id: "uno-online",
    name: "UNO Online",
    mood: "surprised",
    tags: ["card", "multiplayer"],
    src: "https://games.crazygames.com/en_US/uno-online/index.html",
    thumb: thumb("https://games.crazygames.com/en_US/uno-online/index.html"),
  },
  {
    id: "word-wipe",
    name: "Word Wipe",
    mood: "surprised",
    tags: ["word", "puzzle"],
    src: "https://games.crazygames.com/en_US/word-wipe/index.html",
    thumb: thumb("https://games.crazygames.com/en_US/word-wipe/index.html"),
  },
  {
    id: "forest-spirit",
    name: "Forest Spirit",
    mood: "surprised",
    tags: ["strategy", "farm"],
    src: "https://games.crazygames.com/en_US/forest-spirit-farm-fight/index.html",
    thumb: thumb("https://games.crazygames.com/en_US/forest-spirit-farm-fight/index.html"),
  },
  {
    id: "black-light-escape-2",
    name: "Black Light Escape 2",
    mood: "surprised",
    tags: ["escape", "puzzle"],
    src: "https://games.crazygames.com/en_US/black-light-escape-2/index.html",
    thumb: thumb("https://games.crazygames.com/en_US/black-light-escape-2/index.html"),
  },
];

export const MOOD_META = {
  happy:     { emoji: "😄", color: "#f59e0b", label: "Happy",     bg: "#1a1200" },
  angry:     { emoji: "😠", color: "#ef4444", label: "Angry",     bg: "#1a0404" },
  sad:       { emoji: "😢", color: "#7b9fd4", label: "Sad",       bg: "#070f1c" },
  neutral:   { emoji: "😐", color: "#a3a3a3", label: "Neutral",   bg: "#111111" },
  surprised: { emoji: "😲", color: "#a855f7", label: "Surprised", bg: "#0f0818" },
};

export const ALL_MOODS = Object.keys(MOOD_META);
